language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t hassansuhaib/react-text -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hassansuhaib/react-test npm test

after_success:
  - docker build -t hassansuhaib/multi-client ./client
  - docker build -t hassansuhaib/mutli-nginx ./nginx
  - docker build -t hassansuhaib/multi-server ./server
  - docker build -t hassansuhaib/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those iamges and puch them to docker hub
  - docker push hassansuhaib/multi-client
  - docker push hassansuhaib/multi-nginx
  - docker push hassansuhaib/multi-server
  - docker push hassansuhaib/multi-worker
